### ISSUE TITLE
Enter to a file for a 2nd time, does not show the file name in window title

### ISSUE THREAD

**Issue by megatux** [artemanufrij/showmypictures#11]
in _master branch_

first time:
![captura realizada el 2018-04-19 14 45 56](https://user-images.githubusercontent.com/850020/39008917-799dfbe8-43e0-11e8-8774-28b746b0d960.jpeg)

second time:
![captura realizada el 2018-04-19 14 46 07](https://user-images.githubusercontent.com/850020/39008916-796f2548-43e0-11e8-970b-fbbe82a91730.jpeg)

**Comment by artemanufrij** [comment]
@megatux should be fixed in master branch. could you test it please?

**Comment by megatux** [comment]
works great here :+1: Thanks.

**Comment by artemanufrij** [comment]
thanks for feedback!
