### ISSUE TITLE
Feature request - photo export

### ISSUE THREAD

**Issue by curioussavage** [artemanufrij/showmypictures#12]
first off thanks for making the app! First elementary app I have actually paid for.

I was hoping to use it to go through a ton of our photos and make an album of favorites. I guess user created albums could be a different feature request but what I really need is just an option to export a photo. Ie just copy the file from the Library location to another place of my choosing. Right now copying all the files I want will be a little tedious.

**Comment by curioussavage** [comment]
Adding copy to clipboard to the context menu might be even better

**Comment by artemanufrij** [comment]
@curioussavage thank you for your support.

I could add a menu item for export single photo or whole album to a location... Would it hepls you for your usecase?

**Comment by curioussavage** [comment]
I think export single photo would work for me. Unless I can add photos to a custom album an export album option would not work for my particular use case.

**Comment by artemanufrij** [comment]
@curioussavage do you mean something like "Save as..." (just a copy) or "Export" (includes a format chooser)

**Comment by curioussavage** [comment]
I think just copying it would be fine (thinking of my own use case)

**Comment by artemanufrij** [comment]
@curioussavage current master branch has a new Context Menu. Could you test it please?

![save as menuitem](https://user-images.githubusercontent.com/16517095/39873478-5a2c0b1a-546b-11e8-90e1-151c7798a61b.png)

**Comment by curioussavage** [comment]
Tested on my device. Works great! Thanks.

**Comment by artemanufrij** [comment]
@curioussavage Ok. I'm going to prepare a new release... thanks for your support!
