### ISSUE TITLE
Open a file in view mode

### ISSUE THREAD

**Issue by ghost** [artemanufrij/showmypictures#2]
Ability to open a file in view mode would be great. When right clicking on a picture > Open With> Photo Viewer (or setting Photo Viewer as default image viewer), displaying directly the picture. Maybe also for camera raw files, too, not only jpegs, pngs etc.
![screenshot from 2018-01-18 23 31 24](https://user-images.githubusercontent.com/28788471/35122939-2451bc98-fca9-11e7-9204-5b4812068378.jpeg)

**Comment by artemanufrij** [comment]
@cristianmos thank you for your feedback. This is the next feature I will working on.

**Comment by artemanufrij** [comment]
@cristianmos you can test it from master brunch

**Comment by ghost** [comment]
@artemanufrij I don't know how to do that, I'm a photographer :D

**Comment by artemanufrij** [comment]
:) OK, then wait for next release :)

**Comment by artemanufrij** [comment]
released
