### ISSUE TITLE
gif support

### ISSUE THREAD

**Issue by pavlepiramida** [artemanufrij/showmypictures#6]
I know its not a big thing,but is gif support planned?

**Comment by artemanufrij** [comment]
hey @pavlepiramida you can test gif support on current master branch... I would be glad about your feedback.

**Comment by pavlepiramida** [comment]
Give me hour or two and Ill report back!!

**Comment by artemanufrij** [comment]
thanks! don't forget to install `sudo make install` after compile

**Comment by pavlepiramida** [comment]
Awesome work Artem!
Tested with few different gifs and they all work really nice!
Thanks a bunch for this!

**Comment by artemanufrij** [comment]
You are welcome! I will ship new release in AppCenter this weekend…
