### ISSUE TITLE
Allow multiple instances in view mode

### ISSUE THREAD

**Issue by ghost** [artemanufrij/showmypictures#7]
I would like to open another image file, or several, from the file manager in a separate window, if an app window is already opened with an image. Or even better: the possibility of choosing between this behaviour and the current one, when only one image is opened at a time, which most users probably prefer. (I'm using Memories as a photo culling app, that's the reason for the request).

**Comment by artemanufrij** [comment]
@cristianmos good point! I will check that out.

**Comment by artemanufrij** [comment]
@cristianmos could you test current master branch please?

![bildschirmfoto von 2018-02-23 17-48-01](https://user-images.githubusercontent.com/16517095/36605707-c5ffc772-18c1-11e8-9b05-9c8a740abb31.png)

**Comment by ghost** [comment]
Sorry, I have no idea how to do that. I'm not a programmer, I comment because I'm interested in this app.

**Comment by artemanufrij** [comment]
new version was released (0.2.1)... check it out and give me your feedback :smile:

**Comment by ghost** [comment]
Settings button/cog disappeared in view mode. It's only visible if I start the app from the wingpanel or dock. "Use Fast View" is enabled by default, but it has no effect at first. I have to disable it, close the app and re-enable it to be able to open 2 images in 2 separate windows. After I close the app, it has no effect again. (Btw, the new feature of closing the window with Esc is OK.)

**Comment by artemanufrij** [comment]
"Fast View" looks seminar like Main app. Close with escape works only for Fast View

**Comment by ghost** [comment]
So what I was thinking of is something like this: open 2 separate image files from Pantheon Files in 2 separate app windows, in view mode. Like the behaviour of XnView in screenshot.
![screenshot from 2018-02-25 00-1200x1000 41 28](https://user-images.githubusercontent.com/28788471/36635894-68b316d2-19c5-11e8-82df-6760b8099fa5.png)

**Comment by artemanufrij** [comment]
Ah ok... i will check it out

**Comment by artemanufrij** [comment]
hey @cristianmos in next version it will be possible to enable `Multiwindow` mode

![bildschirmfoto von 2018-02-26 21 19 14](https://user-images.githubusercontent.com/16517095/36693200-cc539664-1b3a-11e8-9753-ff8635cffe03.png)

**Comment by artemanufrij** [comment]
@cristianmos could you test current version from AppCenter please...

**Comment by ghost** [comment]
Yes, it works. That's what I was thinking about. Thanks!

**Comment by artemanufrij** [comment]
You are welcome :)
