### ISSUE TITLE
Add functionality to rename files

### ISSUE THREAD

**Issue by megatux** [artemanufrij/showmypictures#9]

**Comment by artemanufrij** [comment]
@megatux not yet, but it would be a useful feature.

**Comment by artemanufrij** [comment]
@megatux could you test current master branch please? Rename by click the Edit button or F2 key
![bildschirmfoto von 2018-04-19 00 32 40](https://user-images.githubusercontent.com/16517095/38961536-43129e2a-4369-11e8-8765-9936a0c29999.png)

**Comment by megatux** [comment]
Tested a little.
* The text field to change the names could be wider,  I mostly rename long random generated filenames or screenshots with date+time+tzone.

Found some issues showing old data.
* After a rename, a dup. image appeared to me. Happened only once:
![dup img after rename](https://user-images.githubusercontent.com/850020/39008544-5f4c8968-43df-11e8-9ac5-07ddb5e64664.jpeg)
* After any refresh and going back to list, the tooltip for file name still displays the old name.

**Comment by artemanufrij** [comment]
@megatux 
* control resized
* tooltip fixed

![bildschirmfoto von 2018-04-19 20 53 42](https://user-images.githubusercontent.com/16517095/39012147-e2fd97a0-4413-11e8-9897-1f7c841109f4.png)

**Comment by megatux** [comment]
Works great here, thanks @artemanufrij

**Comment by artemanufrij** [comment]
@megatux you are welcome!
